lib/snap.ex, lib/snap/request.ex, test/telemetry_test.exs
So that we can keep track of which hosts requests are made to in our
stats expose host and port as part of the telemetry metadata.
=> Add host and port information to telemetry

lib/snap/hit.ex, test/fixtures/search_response.json, test/search_response_test.exs
Finally got around to opening this PR, sorry it took so long (given that it's not a lot of code).
As discussed in https://github.com/breakroom/snap/issues/3 we're adding `matched_queries` and `highlight` to the `Snap.Hit`. We also discussed adding these sort of fields into an `extras` key, but given that by now `explanation` was also added, I don't think it would be consistent.
=> feat: add matched_queries and highlight to Snap.Hit

lib/snap/aggregation.ex, lib/snap/search_response.ex, test/fixtures/search_response_agg.json, test/search_response_test.exs
Hey, thanks for open sourcing, I quite like the simple design of this library!
For my use case, I use the Search API to get aggregations, in a query like:
```elixir
%{
aggs: %{season_values: %{terms: %{field: "season.keyword", size: 100}}},
query: %{terms: %{"season.keyword": ["summer"]}},
size: 0
}
```
However, the aggregation result was being ignored in the SearchResponse, so this PR adds support for that :)
=> Parse aggregations in SearchResponse

lib/snap/bulk/bulk.ex, lib/snap/exceptions/http_error.ex, lib/snap/exceptions/response_error.ex, lib/snap/request.ex
If you make a request that's too large for ES, you'll get an HTTP status 413, with an empty body. This change allows this to bubble up to the user, rather than returning a Jason.DecodeError.
=> Handle HTTP errors with their own exception

README.md, dev.exs, lib/snap.ex, lib/snap/auth/auth.ex, lib/snap/cluster.ex, lib/snap/exceptions/http_error.ex, lib/snap/http_client/adapters/finch.ex, lib/snap/http_client/error.ex, lib/snap/http_client/http_client.ex, lib/snap/http_client/response.ex, lib/snap/request.ex, lib/snap/supervisor.ex, mix.exs, test/auth/plain_test.exs, test/bulk/actions_test.exs, test/http_client/adapters/finch_test.exs, test/search_response_test.exs, test/snap_test.exs, test/telemetry_test.exs
First, congrats on this library! We are using in the company I work for and we quite like it :) 
This MR aims to provide a way for the user to setup his own HTTP client, when they don't want to use Finch. This is specially useful for testing with libs such as [mox](https://github.com/dashbitco/mox)
Besides that, I added two more things that can be useful:
- Added `mix test.all` to run all tests, including the Integration ones
- Added `mix dev` so we can enter IEx with a running dev environment: `iex -S mix dev`
This is a big change, so if you guys think that the lib should be kept simple, feel free to close this MR or create discussions :)
=> Support http client adapters for cluster

lib/snap/aggregation.ex, test/fixtures/search_response_agg.json, test/search_response_test.exs
This PR aims to support more aggregations, namely those that respond with `value`, `doc_count`, and in the case of histograms, `interval`.
It builds off of the great work from @gabrielpra1 in https://github.com/breakroom/snap/pull/6.
=> Adds additional aggregations to handle

mix.exs
**Why:**
Telemetry 1.0 has no changes from version 0.4.3 and most libraries opt for the flixibility of having telemetry **1.0 or 0.4**
In their own words from telemetry changelog: 
> [1.0.0](https://github.com/elixir-telemetry/telemetry/tree/v1.0.0)
> There are no changes in the 1.0.0 release - it marks the stability of the API.
Allowing both versions makes adopting snap into projects much easier, as some libraries still require telemetry 0.4
=> add telemetry 0.4 as backwards compatible option to mix.exs

lib/snap/http_client/http_client.ex
Using `Cluster.get(url)` passes a nil to `HTTPClient.Request` which fails strict typespec enforcement (e.g. when using Hammox):
```
** (EXIT from #PID<0.880.0>) an exception was raised:
** (Hammox.TypeMatchError) 
5th argument value nil does not match 5th parameter's type Snap.HTTPClient.body().
Value nil does not match type binary() | iolist().
```
This PR fixes this by permitting nil bodies in the typespec.
=> Permit nil body in HTTPClient.Request typespec

lib/snap/bulk/bulk.ex
Hi there! 👋 
All the options have defaults, so I think that we could safely define a default empty list for the options. Also, reading the `@doc` looks like it was the intention no? 😄
=> Define opts with default empty keyword list performing bulk

CHANGELOG.md
Fix typo in the changelog and set the latest version to v0.8.1
=> Fix latest release version in CHANGELOG

lib/snap/cluster.ex
=> Support PATCH as an HTTP method on `Snap.Cluster`

lib/snap/indexes.ex, lib/snap/namespace.ex, test/namespace_test.exs
Index hotswapping assumed that there was a namespace, and would fail to run correctly when `index_namespace` was set to `nil` (the default). Fixes #86.
=> Fix index hotswapping with no `index_namespace` set

lib/snap/http_client/adapters/finch.ex
This allows you to use the `accept-encoding` header to handle zipped responses. Quite a few of our requests are chunky and this helps a lot.
=> Support compression in Finch adapter

lib/snap/responses/hit.ex
Hi :) Thanks for the library, appreciate it a lot!
Unfortunately, one of the subtle problems I'm seeing with it is that [Elastic no longer support mapping types.](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html), starting from 8.0.0. They're still required in Snap though, causing all sorts of trouble with mock and/or integration tests and, essentially, forcing us to be stuck with 7.17 version.
This fix eliminates it. I've tested it on private fork and it resolved our need. Should be relatively harmless too!
=> Make Hit type optional

lib/snap.ex, lib/snap/bulk/action.ex, lib/snap/bulk/actions.ex, lib/snap/bulk/bulk.ex, lib/snap/cluster.ex, lib/snap/multi/multi.ex, lib/snap/request.ex, test/bulk/actions_test.exs, test/bulk/bulk_test.exs, test/indexes_test.exs, test/multi/multi_test.exs, test/search_test.exs
It's handy to be able to drop in a faster JSON library, such as Jsonrs, for use cases with very large requests and responses, as JSON encoding and decoding time is greatly reduced. Closes #96.
=> Support pluggable JSON libraries

lib/snap/bulk/action.ex, test/bulk/actions_test.exs
This PR adds routing support to bulk actions (Create, Delete, Index, Update).
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
=> Support routing param in Bulk actions

lib/snap/indexes.ex, test/indexes_test.exs
I need the ability to fetch these mappings and update them and would like to do this without resorting to cobbling together the namespacing with the index name for my tests. This seemed pretty straightforward and the right place to put this.
=> Add ability to update and fetch index the index mapping

.tool-versions, lib/snap/request.ex, test/telemetry_test.exs
It's useful to be able to track the size of the HTTP requests and responses, so added these to the telemetry measurements.
=> Add request + response body bytes to telemetry measurements

lib/snap/namespace.ex, test/namespace_test.exs
When using `Snap.Cluster.Namespace` in tests and the project is using `Task` or things like `Phoenix.LiveView.assign_async/4`, the namespace is not correctly detected.
This change will traverse the current process `$ancestors` to detect if a parent process has a custom namespace set.
=> Implement Process Namespace for Process Ancestors

lib/snap/http_client/adapters/finch.ex, test/http_client/adapters/finch_test.exs
Add a `start_pool_metrics?: true` option to the Finch pool configuration.
`Finch.get_pool_status/2` can then return HTTP client connection pool metrics. For example:
> Finch.get_pool_status(Snap.Test.Cluster.Pool, {:http, "localhost", 9200})
{:ok,
[
%Finch.HTTP1.PoolMetrics{
pool_index: 1,
pool_size: 5,
available_connections: 5,
in_use_connections: 0
}
]}
=> Enable Finch pool metrics

lib/snap/namespace.ex, test/namespace_test.exs
Reverts breakroom/snap#130 - this is causing issues with the test environment that need closer looking at.
=> Revert "Implement Process Namespace for Process Ancestors"

lib/snap/responses/suggest/option.ex, test/search_test.exs
When using a completion suggester via the `search` endpoint three additional fields are returned in each option; `id`, `index` and `source`.
Update the `Snap.Suggest.Option` struct so that these fields are represented making sure that `score` is supported with an underscored and non-underscored key.
Docs: https://opensearch.org/docs/latest/search-plugins/searching-data/autocomplete/#completion-suggester
=> Add support for completion suggests
